- name: make etcd data directory
  file: path=/var/lib/etcd state=directory
- name: make etcd date file
  file: path=/var/lib/etcd/k8s.etcd state=directory
- name: mkdir cfg directory
  file: path=/opt/kubernetes/cfg state=directory
- name: copy etcd cfg file
  copy: src=roles/etcd/files/etcd.conf dest=/opt/kubernetes/cfg
- name: copy etcd file
  copy: src=roles/etcd/files/etcd dest=/opt/kubernetes/bin/ mode=766
- name: copy etcdctl file
  copy: src=roles/etcd/files/etcdctl dest=/usr/local/bin mode=766
- name: copy etcd service file
  copy: src=roles/etcd/files/etcd.service dest=/usr/lib/systemd/system/
- name: start etcd
  shell: systemctl daemon-reload && systemctl start etcd && systemctl enable etcd
- name: gen docker network
  shell: /usr/local/bin/etcdctl mk /coreos.com/network/config '{"Network":"172.17.0.0/16"}'
